import { PrismaClient } from '@prisma/client';
const db = new PrismaClient({ datasources: { db: { url: process.env.DIRECT_URL } } });
const q = async (l: string, s: string) => { try { const r: any = await db.$queryRawUnsafe(s); console.log(l, Number(r[0].n)); } catch(e:any){ console.log(l, 'ERR', e.message.split('\n')[0]); } };
await q('users        ', 'SELECT count(*) n FROM users');
await q('components    ', 'SELECT count(*) n FROM components');
await q('item_variants ', 'SELECT count(*) n FROM item_variants');
await q('items         ', 'SELECT count(*) n FROM items');
await q('warehouses    ', 'SELECT count(*) n FROM warehouses');
await q('item_lots     ', 'SELECT count(*) n FROM item_lots');
await q('products      ', 'SELECT count(*) n FROM products');
await q('pcbs          ', 'SELECT count(*) n FROM pcbs');
await db.$disconnect();
