// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI (db pull / migrate / studio) manages schema as the OWNER, so it
    // can create _prisma_migrations, see every object, and bypass RLS. The running
    // app never uses this — it connects as erp_app via DATABASE_URL (src/lib/prisma.ts).
    url: process.env["DIRECT_URL"],
  },
});
