import type { Pcb } from "./types"

// Canonical PCBs. `lines[].componentId` references COMPONENTS; products
// reference these by `id`. `usedIn` is derived from products via selectors.
export const PCBS: Pcb[] = [
  {
    id: "audio-pcb",
    name: "Audio PCB",
    description: "Voice and audio signal processing board",
    layers: 4,
    status: "Active",
    componentsCount: 58,
    stockCount: 120,
    lines: [
      { componentId: "audio-codec", qty: 1 },
      { componentId: "resistor-10k", qty: 20 },
      { componentId: "capacitor-100uf", qty: 10 },
      { componentId: "led-green", qty: 4 },
      { componentId: "connector", qty: 3 },
    ],
  },
  {
    id: "gsm-pcb",
    name: "GSM PCB",
    description: "Mobile network connectivity module board",
    layers: 6,
    status: "Active",
    componentsCount: 75,
    stockCount: 80,
    lines: [
      { componentId: "gsm-chip", qty: 1 },
      { componentId: "sim-holder", qty: 1 },
      { componentId: "capacitor-10uf", qty: 15 },
      { componentId: "antenna-connector", qty: 2 },
    ],
  },
  {
    id: "display-pcb",
    name: "Display PCB",
    description: "LCD screen driver interface board",
    layers: 2,
    status: "Active",
    componentsCount: 40,
    stockCount: 150,
    lines: [
      { componentId: "display-ic", qty: 1 },
      { componentId: "led-backlight-driver", qty: 1 },
      { componentId: "leds", qty: 12 },
      { componentId: "ribbon-connector", qty: 1 },
    ],
  },
  {
    id: "power-pcb",
    name: "Power PCB",
    description: "Voltage regulation and power distribution board",
    layers: 2,
    status: "Prototype",
    componentsCount: 32,
    stockCount: 200,
    lines: [
      { componentId: "power-ic", qty: 1 },
      { componentId: "inductor-4.7uh", qty: 3 },
      { componentId: "capacitors-22uf", qty: 8 },
      { componentId: "fuse-2a", qty: 2 },
    ],
  },
  {
    id: "main-pcb",
    name: "Main PCB",
    description: "Primary controller and DSP board",
    layers: 8,
    status: "Active",
    componentsCount: 80,
    stockCount: 50,
    lines: [
      { componentId: "dsp-chip", qty: 1 },
      { componentId: "microcontroller", qty: 1 },
      { componentId: "sram-512kb", qty: 2 },
      { componentId: "oscillator-24mhz", qty: 1 },
    ],
  },
  {
    id: "memory-pcb",
    name: "Memory PCB",
    description: "Storage and flash memory expansion board",
    layers: 4,
    status: "Active",
    componentsCount: 45,
    stockCount: 90,
    lines: [
      { componentId: "flash-memory", qty: 2 },
      { componentId: "sd-card-slot", qty: 1 },
      { componentId: "resistor-10k", qty: 12 },
    ],
  },
  {
    id: "interface-pcb",
    name: "Interface PCB",
    description: "External I/O and USB interface board",
    layers: 4,
    status: "Active",
    componentsCount: 28,
    stockCount: 110,
    lines: [
      { componentId: "usb-controller", qty: 1 },
      { componentId: "led-green", qty: 3 },
    ],
  },
]
