import type { Supplier } from "./types"

// Canonical suppliers / distributors. Referenced by component offers and
// purchase records via `id`.
export const SUPPLIERS: Supplier[] = [
  {
    id: "abc-electronics",
    name: "ABC Electronics",
    description: "Elite components distributor and logistics partner.",
    contact: "Rajesh Kumar",
    email: "contact@abcelectronics.in",
    phone: "+91 80 4912 3456",
    address: "Plot 42, Electronic City Phase 1, Bangalore, Karnataka, India",
    terms: "Net 30",
    rating: 4.7,
    status: "Active",
  },
  {
    id: "xyz-components",
    name: "XYZ Components",
    description: "Bulk electronic component vendor and direct importer.",
    contact: "Sarah Jenkins",
    email: "sales@xyzcomponents.com",
    phone: "+91 22 6789 1234",
    address: "18 Industrial Estate, Andheri East, Mumbai, Maharashtra, India",
    terms: "Net 15",
    rating: 4.4,
    status: "Active",
  },
  {
    id: "powertech",
    name: "PowerTech",
    description: "High-reliability industrial power electronics and passives.",
    contact: "Marc DuPont",
    email: "orders@powertech.io",
    phone: "+91 44 2233 7788",
    address: "7 Ambattur Industrial Road, Chennai, Tamil Nadu, India",
    terms: "Net 30",
    rating: 4.6,
    status: "Active",
  },
  {
    id: "semiconductors-corp",
    name: "Semiconductors Corp",
    description: "Primary distributor of ICs and microcontrollers.",
    contact: "Jane Doe",
    email: "support@semicorp.com",
    phone: "+91 40 6655 4433",
    address: "Tower B, HITEC City, Hyderabad, Telangana, India",
    terms: "Net 45",
    rating: 4.8,
    status: "Active",
  },
  {
    id: "led-depot",
    name: "LED Depot",
    description: "Supplier of LEDs and optoelectronics components.",
    contact: "John Smith",
    email: "hello@leddepot.in",
    phone: "+91 79 2468 1357",
    address: "55 GIDC Estate, Ahmedabad, Gujarat, India",
    terms: "Net 15",
    rating: 4.2,
    status: "Active",
  },
  {
    id: "fastpcbs-ltd",
    name: "FastPCBs Ltd",
    description: "PCB fabrication and layout prototyping services.",
    contact: "Alice Johnson",
    email: "fab@fastpcbs.com",
    phone: "+91 120 432 9876",
    address: "Sector 63, Noida, Uttar Pradesh, India",
    terms: "Advance 50%",
    rating: 4.9,
    status: "Active",
  },
  {
    id: "mouser",
    name: "Mouser",
    description: "Global authorized distributor of semiconductors and electronic components.",
    contact: "David Lee",
    email: "india@mouser.com",
    phone: "+91 80 6000 1100",
    address: "1000 North Main St (India Desk), Bangalore, Karnataka, India",
    terms: "Net 30",
    rating: 4.8,
    status: "Active",
  },
  {
    id: "digikey",
    name: "DigiKey",
    description: "Broadline distributor of electronic components and automation products.",
    contact: "Emily Carter",
    email: "apac@digikey.com",
    phone: "+91 80 6000 2200",
    address: "APAC Distribution Hub, Bangalore, Karnataka, India",
    terms: "Net 30",
    rating: 4.8,
    status: "Active",
  },
  {
    id: "arrow",
    name: "Arrow",
    description: "Global technology distributor of components and enterprise solutions.",
    contact: "Michael Brown",
    email: "india@arrow.com",
    phone: "+91 22 6111 9000",
    address: "Bandra Kurla Complex, Mumbai, Maharashtra, India",
    terms: "Net 45",
    rating: 4.5,
    status: "Active",
  },
  {
    id: "delta-components",
    name: "Delta Components",
    description: "Regional distributor of connectors and electromechanical parts.",
    contact: "Priya Nair",
    email: "sales@deltacomponents.in",
    phone: "+91 484 277 6655",
    address: "12 Seaport Road, Kochi, Kerala, India",
    terms: "Net 15",
    rating: 4.1,
    status: "Active",
  },
]
